services:
  postgres:
    image: postgres:16
    container_name: gym-postgres
    environment:
      POSTGRES_USER: gym_user
      POSTGRES_PASSWORD: gym_pass
    ports:
      - "5432:5432"
    volumes:
      - gym_pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  gym_pgdata: