spring.profiles.active=local
# Common settings
# Actuator
management.endpoints.web.exposure.include=health,prometheus
# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
# OSIV: (Best practice)
spring.jpa.open-in-view=false
# Налаштування для H2 (тільки для local)
spring.h2.console.enabled=true