spring.profiles.active=local
# Common settings
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
# OSIV: (Best practice)
spring.jpa.open-in-view=false
# settings for H2 (only for local)
spring.h2.console.enabled=true
# --- Actuator Configuration ---
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always