# PostgreSQL STG configuration
spring.datasource.url=${STG_DB_URL:jdbc:postgresql://localhost:5432/gym_stg}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${STG_DB_USERNAME:gym_user}
spring.datasource.password=${STG_DB_PASSWORD:gym_pass}
# Hibernate PROD-like configuration (Security)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false