# ===== Datasource (PostgreSQL) =====
spring.profiles.active=local
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# ===== JWT Configuration =====
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=36000000
# Brute Force Protection
security.brute-force.max-attempts=3
security.brute-force.block-duration-minutes=5
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
# ===== Application Name & Eureka Client =====
spring.application.name=gym-main-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.registry-fetch-interval-seconds=3
# ===== Resilience4j Circuit Breaker Configuration =====
resilience4j.circuitbreaker.instances.workloadService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.workloadService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.workloadService.failureRateThreshold=50.0
resilience4j.circuitbreaker.instances.workloadService.slowCallRateThreshold=100.0
resilience4j.circuitbreaker.instances.workloadService.slowCallDurationThreshold=2s
resilience4j.circuitbreaker.instances.workloadService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.workloadService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.workloadService.automaticTransitionFromOpenToHalfOpenEnabled=true

# ===== ActiveMQ =====
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

# Черга для workload-подій
gym.messaging.workload-queue=workload.queue