# ===== Datasource (PostgreSQL) =====
spring.profiles.active=local
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# ===== JWT Configuration =====
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=36000000
# Brute Force Protection
security.brute-force.max-attempts=3
security.brute-force.block-duration-minutes=5
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
# ===== Application Name & Eureka Client =====
spring.application.name=gym-main-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.registry-fetch-interval-seconds=3
# ===== ActiveMQ =====
# ===== ActiveMQ =====
spring.activemq.broker-url=${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
spring.activemq.user=${ACTIVEMQ_USER:admin}
spring.activemq.password=${ACTIVEMQ_PASSWORD:admin}
# Черга для workload-подій
gym.messaging.workload-queue=workload.queue
gym.messaging.workload-dlq=workload.dlq