# ===== Datasource (PostgreSQL) =====
spring.profiles.active=local
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# ===== JWT Configuration =====
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=36000000
# Brute Force Protection
security.brute-force.max-attempts=3
security.brute-force.block-duration-minutes=5