# PostgreSQL PROD configuration
spring.datasource.url=${PROD_DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${PROD_DB_USERNAME}
spring.datasource.password=${PROD_DB_PASSWORD}
# Hibernate PROD configuration (Security)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false