server.port=8081
spring.application.name=trainer-workload-service
security.jwt.secret=${JWT_SECRET}
# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# ===== ActiveMQ =====
spring.activemq.broker-url=${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
spring.activemq.user=${ACTIVEMQ_USER:admin}
spring.activemq.password=${ACTIVEMQ_PASSWORD:admin}
gym.messaging.workload-dlq=workload.dlq
gym.messaging.workload-queue=workload.queue