server.port=8081
spring.application.name=trainer-workload-service
security.jwt.secret=${JWT_SECRET}
# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

gym.messaging.workload-queue=workload.queue